# Generated by Django 5.1.7 on 2025-04-07 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disks.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('composer', models.CharField(max_length=255, null=True)),
                ('milliseconds', models.IntegerField()),
                ('bytes', models.IntegerField()),
                ('unitPrice', models.DecimalField(decimal_places=1, max_digits=3)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disks.album')),
            ],
        ),
    ]
